#Numpy


In [1]:

# (1) print array , data type , size of the array & print sorted array :
import numpy as np

arr=np.array([6,9,2,5])

print("number: ",arr)
print("data type of array: ",arr.dtype)
print("size: ",np.size(arr))
print("sorted array: ",np.sort(arr))

number:  [6 9 2 5]
data type of array:  int64
size:  4
sorted array:  [2 5 6 9]


In [2]:
# (2) addition & multiplication of numpy array :
arr_1=np.array([5,3,1])
arr_2=np.array([6,4,2])
print("addition of 2 array:",arr_1+arr_2)
print("multiplication of 2 array:",arr_1*arr_2)

addition of 2 array: [11  7  3]
multiplication of 2 array: [30 12  2]


In [2]:
#Multidimensional 
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr[1, 2])


6


In [3]:
# Mathematical Functions

import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(np.sum(arr))
print(np.mean(arr))
print(np.std(arr))

15
3.0
1.4142135623730951


In [5]:
import numpy as np
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
print(np.add(matrix1, matrix2))

[[ 6  8]
 [10 12]]


In [14]:
import numpy as np

print(np.random.rand(3))
print(np.random.randint(0, 10, 20))

[0.1915258  0.12713772 0.21832703]
[8 2 5 2 9 3 0 9 7 4 8 7 2 2 1 0 1 5 3 0]
